services:
  account-db:
    image: postgres:latest
    container_name: account_db
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./AccountService/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql